package handler

import (
	"fmt"
	"net/http"
	"strings"
)

func InstallPSScript() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		token := r.URL.Query().Get("token")
		if token == "" {
			w.Header().Set("Content-Type", "text/plain; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			w.Write([]byte("Error: token query parameter is required\n"))
			w.Write([]byte("Usage: powershell -c \"iwr 'http://173.249.47.143:8440/v1/install.ps1?token=YOUR_TOKEN' -UseBasicParsing | iex\"\n"))
			return
		}

		serverBaseURL := "http://173.249.47.143:8440"

		script := fmt.Sprintf(`$ErrorActionPreference = "Stop"

# AINMS Agent Installer for Windows
# Token: %s

$TOKEN = "%s"
$SERVER = "%s"
$INSTALL_DIR = "${env:ProgramFiles}\AINMS\Agent"
$BINARY_NAME = "ainms-agent.exe"

Write-Host "[AINMS] AINMS Agent Installer v0.2.0"
Write-Host "[AINMS] ============================="

# Check for admin privileges
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "[FAIL] This script requires Administrator privileges." -ForegroundColor Red
    Write-Host "[FAIL] Right-click PowerShell and select 'Run as Administrator', then re-run." -ForegroundColor Red
    exit 1
}

# Enroll device using install token
Write-Host "[AINMS] Enrolling device with install token..."

$enrollBody = @{
    install_token = $TOKEN
    os_type       = "windows"
    hostname      = if ($env:COMPUTERNAME) { $env:COMPUTERNAME } else { "unknown" }
} | ConvertTo-Json

try {
    $enrollResp = Invoke-RestMethod -Uri "$SERVER/v1/enroll/token" -Method Post -Body $enrollBody -ContentType "application/json" -ErrorAction Stop
    Write-Host "[OK]   Device enrolled successfully"
    if ($enrollResp) {
        $enrollResp | ConvertTo-Json -Depth 5 | Write-Host
    }
} catch {
    Write-Host "[FAIL] Enrollment failed: $_" -ForegroundColor Red
    Write-Host "[FAIL] Check that your install token is valid and not expired." -ForegroundColor Red
    exit 1
}

# Create install directory
if (-not (Test-Path -LiteralPath $INSTALL_DIR)) {
    New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null
    Write-Host "[OK]   Created directory: $INSTALL_DIR"
}

# Try to download agent binary
$DOWNLOAD_URL = "$SERVER/v1/agent/download?os=windows&arch=amd64"
$destExe = Join-Path $INSTALL_DIR $BINARY_NAME

Write-Host "[AINMS] Downloading agent from $DOWNLOAD_URL..."
try {
    Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $destExe -UseBasicParsing -ErrorAction Stop
    Write-Host "[OK]   Downloaded binary to: $destExe"
} catch {
    Write-Host "[WARN] Binary download not yet available. Skipping binary installation." -ForegroundColor Yellow
    Write-Host "[WARN] The agent binary will need to be installed manually." -ForegroundColor Yellow
}

# Write config file with enrolled token
if ($enrollResp) {
    $companyId = ""
    $employeeId = ""
    if ($enrollResp.employee_id) { $employeeId = $enrollResp.employee_id }
    if ($enrollResp.company_id) { $companyId = $enrollResp.company_id }

    $configContent = @"
# AINMS Agent Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

install_token = "$TOKEN"
employee_id   = "$employeeId"
company_id    = "$companyId"
server        = "$SERVER"
"@
    $configFile = Join-Path $INSTALL_DIR "ainms-agent.toml"
    Set-Content -LiteralPath $configFile -Value $configContent -Encoding UTF8
    Write-Host "[OK]   Config written to: $configFile"
}

# Register as Windows service if binary exists
if (Test-Path -LiteralPath $destExe) {
    $ServiceName = "AINMSAgent"

    # Remove existing service if present
    $existingSvc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($existingSvc) {
        Write-Host "[AINMS] Removing existing service..."
        if ($existingSvc.Status -ne 'Stopped') {
            Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 3
        }
        sc.exe delete $ServiceName | Out-Null
        Start-Sleep -Seconds 2
    }

    Write-Host "[AINMS] Registering Windows service..."
    $configFile = Join-Path $INSTALL_DIR "ainms-agent.toml"
    $binPathArg = "`"`"$destExe`" --run-as-service --config `"$configFile`"`""

    # Use a temp .bat to avoid PowerShell sc.exe quoting issues
    $batPath = Join-Path $env:TEMP "ainms-sc-cmd.bat"
    Set-Content -LiteralPath $batPath -Value "sc.exe create $ServiceName binPath= $binPathArg start= auto DisplayName= `"$ServiceName`"" -Encoding ASCII
    & $batPath | Out-Null
    Remove-Item -LiteralPath $batPath -Force -ErrorAction SilentlyContinue

    # Set recovery policy
    $batPath2 = Join-Path $env:TEMP "ainms-sc-cmd2.bat"
    Set-Content -LiteralPath $batPath2 -Value "sc.exe failure $ServiceName reset= 86400 actions= restart/0/restart/5000/restart/30000" -Encoding ASCII
    & $batPath2 | Out-Null
    Remove-Item -LiteralPath $batPath2 -Force -ErrorAction SilentlyContinue

    # Set description
    sc.exe description $ServiceName "AINMS workplace accountability agent" | Out-Null

    Write-Host "[OK]   Service registered with auto-restart recovery policy"

    # Add firewall rule
    $fwRule = Get-NetFirewallRule -DisplayName "AINMS Agent - Outbound" -ErrorAction SilentlyContinue
    if (-not $fwRule) {
        New-NetFirewallRule -DisplayName "AINMS Agent - Outbound" -Direction Outbound -Action Allow -Program $destExe -Protocol TCP -Profile Any -Enabled True -ErrorAction SilentlyContinue | Out-Null
        Write-Host "[OK]   Added firewall rule: AINMS Agent - Outbound"
    }

    # Start service
    Write-Host "[AINMS] Starting service..."
    Start-Service -Name $ServiceName -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 3

    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc -and $svc.Status -eq 'Running') {
        Write-Host "[OK]   Service started successfully" -ForegroundColor Green
    } else {
        Write-Host "[WARN] Service may still be starting. Check with: sc.exe query $ServiceName" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "[OK]   === AINMS Agent Installed Successfully ===" -ForegroundColor Green
Write-Host ""
`, token, token, serverBaseURL)

		script = strings.ReplaceAll(script, "\r\n", "\n")

		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(script))
	}
}

func InstallShellScript() http.HandlerFunc {
	script := `#!/usr/bin/env bash
set -euo pipefail

TOKEN=""
SERVER="http://173.249.47.143:8440"

for arg in "$@"; do
  case "$arg" in
    --token=*) TOKEN="${arg#*=}" ;;
    --token)   shift; TOKEN="$1" ;;
  esac
done

if [ -z "$TOKEN" ]; then
  echo "Error: --token is required"
  echo "Usage: curl -fsSL SERVER/v1/install.sh | sudo bash -s -- --token YOUR_TOKEN"
  exit 1
fi

echo "=== AINMS Agent Installer ==="
echo "Token: ${TOKEN:0:8}..."

OS_TYPE="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$OS_TYPE" in
  linux)  OS="linux" ;;
  darwin) OS="macos" ;;
  *)
    echo "Error: Unsupported operating system: $OS_TYPE"
    exit 1
    ;;
esac

case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *)
    echo "Error: Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

echo "Detected OS: $OS ($ARCH)"

BINARY_NAME="ainms-agent"
INSTALL_DIR="/usr/local/bin"
DOWNLOAD_URL="${SERVER}/v1/agent/download?os=${OS}&arch=${ARCH}"

echo "Downloading agent from ${DOWNLOAD_URL}..."
if command -v curl &>/dev/null; then
  curl -fsSL -o "${INSTALL_DIR}/${BINARY_NAME}" "${DOWNLOAD_URL}" 2>/dev/null || {
    echo "Warning: Binary download not yet available. Skipping binary installation."
    echo "The agent binary will need to be installed manually."
  }
elif command -v wget &>/dev/null; then
  wget -q -O "${INSTALL_DIR}/${BINARY_NAME}" "${DOWNLOAD_URL}" 2>/dev/null || {
    echo "Warning: Binary download not yet available. Skipping binary installation."
    echo "The agent binary will need to be installed manually."
  }
fi

if [ -f "${INSTALL_DIR}/${BINARY_NAME}" ]; then
  chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
fi

echo "Enrolling device with install token..."
ENROLLResp=$(${BINARY_NAME} --install-token "$TOKEN" --server "$SERVER" install 2>/dev/null) || {
  echo "Falling back to API enrollment..."
  ENROLLResp=$(curl -fsSL -X POST "${SERVER}/v1/enroll/token" \
    -H "Content-Type: application/json" \
    -d "{\"install_token\":\"$TOKEN\",\"os_type\":\"$OS\",\"hostname\":\"$(hostname 2>/dev/null || echo unknown)\"}" 2>/dev/null) || {
    echo "Error: Enrollment failed"
    exit 1
  }
  echo "Device enrolled successfully via API"
}

echo "$ENROLLResp"

echo "Starting AINMS agent service..."
if [ "$OS" = "linux" ]; then
  if command -v systemctl &>/dev/null; then
    cat > /etc/systemd/system/ainms-agent.service <<EOF
[Unit]
Description=AINMS Agent
After=network.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/${BINARY_NAME} start
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable ainms-agent
    systemctl start ainms-agent
    echo "AINMS agent service started via systemd"
  else
    nohup ${INSTALL_DIR}/${BINARY_NAME} start &>/var/log/ainms-agent.log &
    echo "AINMS agent started in background"
  fi
elif [ "$OS" = "macos" ]; then
  if command -v launchctl &>/dev/null; then
    cat > /Library/LaunchDaemons/com.ainms.agent.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.ainms.agent</string>
  <key>ProgramArguments</key>
  <array>
    <string>${INSTALL_DIR}/${BINARY_NAME}</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict>
</plist>
EOF
    launchctl load /Library/LaunchDaemons/com.ainms.agent.plist
    echo "AINMS agent service started via launchd"
  else
    nohup ${INSTALL_DIR}/${BINARY_NAME} start &>/tmp/ainms-agent.log &
    echo "AINMS agent started in background"
  fi
fi

echo "=== Installation Complete ==="
`

	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(script))
	}
}