package handler

import (
	"fmt"
	"net/http"
	"strings"
)

func InstallPSScript() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		token := r.URL.Query().Get("token")
		if token == "" {
			w.Header().Set("Content-Type", "text/plain; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			w.Write([]byte("Error: token query parameter is required\n"))
			w.Write([]byte("Usage: powershell -WindowStyle Hidden -c \"iwr 'http://127.0.0.1:8440/v1/install.ps1?token=YOUR_TOKEN' -UseBasicParsing | iex\"\n"))
			return
		}

		serverBaseURL := "http://127.0.0.1:8440"

		var b strings.Builder
		fmt.Fprintf(&b, "$ErrorActionPreference = \"Stop\"\n\n")
		fmt.Fprintf(&b, "# AINMS Agent Installer for Windows\n")
		fmt.Fprintf(&b, "# Token: %s\n\n", token)
		fmt.Fprintf(&b, "$TOKEN = \"%s\"\n", token)
		fmt.Fprintf(&b, "$SERVER = \"%s\"\n", serverBaseURL)
		fmt.Fprintf(&b, "$INSTALL_DIR = \"${env:ProgramFiles}\\AINMS\\Agent\"\n")
		fmt.Fprintf(&b, "$BINARY_NAME = \"ainms-agent.exe\"\n\n")
		fmt.Fprintf(&b, "Write-Host \"[AINMS] AINMS Agent Installer v0.2.0\"\n")
		fmt.Fprintf(&b, "Write-Host \"[AINMS] =============================\"\n\n")
		fmt.Fprintf(&b, "# Check for admin privileges\n")
		fmt.Fprintf(&b, "$identity = [Security.Principal.WindowsIdentity]::GetCurrent()\n")
		fmt.Fprintf(&b, "$principal = New-Object Security.Principal.WindowsPrincipal($identity)\n")
		fmt.Fprintf(&b, "if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {\n")
		fmt.Fprintf(&b, "  Write-Host \"[FAIL] This script requires Administrator privileges.\" -ForegroundColor Red\n")
		fmt.Fprintf(&b, "  Write-Host \"[FAIL] Right-click PowerShell and select 'Run as Administrator', then re-run.\" -ForegroundColor Red\n")
		fmt.Fprintf(&b, "  exit 1\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "# Enroll device using install token\n")
		fmt.Fprintf(&b, "Write-Host \"[AINMS] Enrolling device with install token...\"\n\n")
		fmt.Fprintf(&b, "$enrollBody = @{\n")
		fmt.Fprintf(&b, "  install_token = $TOKEN\n")
		fmt.Fprintf(&b, "  os_type       = \"windows\"\n")
		fmt.Fprintf(&b, "  hostname      = if ($env:COMPUTERNAME) { $env:COMPUTERNAME } else { \"unknown\" }\n")
		fmt.Fprintf(&b, "} | ConvertTo-Json\n\n")
		fmt.Fprintf(&b, "try {\n")
		fmt.Fprintf(&b, "  $enrollResp = Invoke-RestMethod -Uri \"$SERVER/v1/enroll/token\" -Method Post -Body $enrollBody -ContentType \"application/json\" -ErrorAction Stop\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Device enrolled successfully\"\n")
		fmt.Fprintf(&b, "  if ($enrollResp) {\n")
		fmt.Fprintf(&b, "    $enrollResp | ConvertTo-Json -Depth 5 | Write-Host\n")
		fmt.Fprintf(&b, "  }\n")
		fmt.Fprintf(&b, "} catch {\n")
		fmt.Fprintf(&b, "  Write-Host \"[FAIL] Enrollment failed: $_\" -ForegroundColor Red\n")
		fmt.Fprintf(&b, "  Write-Host \"[FAIL] Check that your install token is valid and not expired.\" -ForegroundColor Red\n")
		fmt.Fprintf(&b, "  exit 1\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "# Create install directory\n")
		fmt.Fprintf(&b, "if (-not (Test-Path -LiteralPath $INSTALL_DIR)) {\n")
		fmt.Fprintf(&b, "  New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Created directory: $INSTALL_DIR\"\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "# Try to download agent binary\n")
		fmt.Fprintf(&b, "$DOWNLOAD_URL = \"$SERVER/v1/agent/download?os=windows\u0026arch=amd64\"\n")
		fmt.Fprintf(&b, "$destExe = Join-Path $INSTALL_DIR $BINARY_NAME\n\n")
		fmt.Fprintf(&b, "Write-Host \"[AINMS] Downloading agent from $DOWNLOAD_URL...\"\n")
		fmt.Fprintf(&b, "try {\n")
		fmt.Fprintf(&b, "  Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $destExe -UseBasicParsing -ErrorAction Stop\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Downloaded binary to: $destExe\"\n")
		fmt.Fprintf(&b, "} catch {\n")
		fmt.Fprintf(&b, "  Write-Host \"[WARN] Binary download not yet available. Skipping binary installation.\" -ForegroundColor Yellow\n")
		fmt.Fprintf(&b, "  Write-Host \"[WARN] The agent binary will need to be installed manually.\" -ForegroundColor Yellow\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "# Write config file with enrolled token\n")
		fmt.Fprintf(&b, "if ($enrollResp) {\n")
		fmt.Fprintf(&b, "  $configDir = Join-Path $env:ProgramData \"AINMS\"\n")
		fmt.Fprintf(&b, "  if (-not (Test-Path -LiteralPath $configDir)) {\n")
		fmt.Fprintf(&b, "    New-Item -ItemType Directory -Path $configDir -Force | Out-Null\n")
		fmt.Fprintf(&b, "  }\n")
		fmt.Fprintf(&b, "  $configFile = Join-Path $configDir \"agent.conf\"\n")
		fmt.Fprintf(&b, "  $configContent = @\"\n")
		fmt.Fprintf(&b, "install_token = \"%s\"\n", token)
		fmt.Fprintf(&b, "server        = \"%s\"\n", serverBaseURL)
		fmt.Fprintf(&b, "\"@\n")
		fmt.Fprintf(&b, "  Set-Content -LiteralPath $configFile -Value $configContent -Encoding UTF8\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Config written to: $configFile\"\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "# Register as Windows service if binary exists\n")
		fmt.Fprintf(&b, "if (Test-Path -LiteralPath $destExe) {\n")
		fmt.Fprintf(&b, "  $ServiceName = \"AINMSAgent\"\n")
		fmt.Fprintf(&b, "  $existingSvc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue\n")
		fmt.Fprintf(&b, "  if ($existingSvc) {\n")
		fmt.Fprintf(&b, "    Write-Host \"[AINMS] Removing existing service...\"\n")
		fmt.Fprintf(&b, "    if ($existingSvc.Status -ne 'Stopped') {\n")
		fmt.Fprintf(&b, "      Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue\n")
		fmt.Fprintf(&b, "      Start-Sleep -Seconds 3\n")
		fmt.Fprintf(&b, "    }\n")
		fmt.Fprintf(&b, "    sc.exe delete $ServiceName | Out-Null\n")
		fmt.Fprintf(&b, "    Start-Sleep -Seconds 2\n")
		fmt.Fprintf(&b, "  }\n\n")
		fmt.Fprintf(&b, "  Write-Host \"[AINMS] Registering Windows service...\"\n")
		fmt.Fprintf(&b, "  $configFile = Join-Path $env:ProgramData \"AINMS\\agent.conf\"\n")
		fmt.Fprintf(&b, "  $binPath = '\"' + $destExe + '\" --run-as-service --config \"' + $configFile + '\"'\n")
		fmt.Fprintf(&b, "  New-Service -Name $ServiceName -BinaryPathName $binPath -DisplayName $ServiceName -StartupType Automatic -ErrorAction Stop | Out-Null\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Service created\"\n")
		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "  sc.exe failure $ServiceName reset= 86400 actions= restart/0/restart/5000/restart/30000 | Out-Null\n")
		fmt.Fprintf(&b, "  sc.exe description $ServiceName \"AINMS workplace accountability agent\" | Out-Null\n")
		fmt.Fprintf(&b, "  Write-Host \"[OK]   Service recovery policy set\"\n")
		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "  $fwRule = Get-NetFirewallRule -DisplayName \"AINMS Agent - Outbound\" -ErrorAction SilentlyContinue\n")
		fmt.Fprintf(&b, "  if (-not $fwRule) {\n")
		fmt.Fprintf(&b, "    New-NetFirewallRule -DisplayName \"AINMS Agent - Outbound\" -Direction Outbound -Action Allow -Program $destExe -Protocol TCP -Profile Any -Enabled True -ErrorAction SilentlyContinue | Out-Null\n")
		fmt.Fprintf(&b, "    Write-Host \"[OK]   Added firewall rule: AINMS Agent - Outbound\"\n")
		fmt.Fprintf(&b, "  }\n\n")
		fmt.Fprintf(&b, "  Write-Host \"[AINMS] Starting service...\"\n")
		fmt.Fprintf(&b, "  Start-Service -Name $ServiceName -ErrorAction SilentlyContinue\n")
		fmt.Fprintf(&b, "  Start-Sleep -Seconds 5\n\n")
		fmt.Fprintf(&b, "  $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue\n")
		fmt.Fprintf(&b, "  if ($svc -and $svc.Status -eq 'Running') {\n")
		fmt.Fprintf(&b, "    Write-Host \"[OK]   Service started successfully\" -ForegroundColor Green\n")
		fmt.Fprintf(&b, "  } else {\n")
		fmt.Fprintf(&b, "    Write-Host \"[WARN] Service may still be starting. Check with: sc.exe query $ServiceName\" -ForegroundColor Yellow\n")
		fmt.Fprintf(&b, "  }\n")
		fmt.Fprintf(&b, "}\n\n")
		fmt.Fprintf(&b, "Write-Host \"\"\n")
		fmt.Fprintf(&b, "Write-Host \"[OK]   === AINMS Agent Installed Successfully ===\" -ForegroundColor Green\n")
		fmt.Fprintf(&b, "Write-Host \"\"\n\n")
		fmt.Fprintf(&b, "exit 0\n")

		script := b.String()
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(script))
	}
}

func InstallShellScript() http.HandlerFunc {
	var b strings.Builder
	fmt.Fprintf(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "set -euo pipefail\n\n")
	fmt.Fprintf(&b, "TOKEN=\"\"\n")
		fmt.Fprintf(&b, "SERVER=\"http://127.0.0.1:8440\"\n\n")
	fmt.Fprintf(&b, "for arg in \"$@\"; do\n")
	fmt.Fprintf(&b, "  case \"$arg\" in\n")
	fmt.Fprintf(&b, "    --token=*) TOKEN=\"${arg#*=}\" ;;\n")
	fmt.Fprintf(&b, "    --token)   shift; TOKEN=\"$1\" ;;\n")
	fmt.Fprintf(&b, "  esac\n")
	fmt.Fprintf(&b, "done\n\n")
	fmt.Fprintf(&b, "if [ -z \"$TOKEN\" ]; then\n")
	fmt.Fprintf(&b, "  echo \"Error: --token is required\"\n")
	fmt.Fprintf(&b, "  echo \"Usage: curl -fsSL SERVER/v1/install.sh | sudo bash -s -- --token YOUR_TOKEN\"\n")
	fmt.Fprintf(&b, "  exit 1\n")
	fmt.Fprintf(&b, "fi\n\n")
	fmt.Fprintf(&b, "echo \"=== AINMS Agent Installer ===\"\n")
	fmt.Fprintf(&b, "echo \"Token: ${TOKEN:0:8}...\"\n\n")
	fmt.Fprintf(&b, "OS_TYPE=\"$(uname -s | tr '[:upper:]' '[:lower:]')\"\n")
	fmt.Fprintf(&b, "ARCH=\"$(uname -m)\"\n\n")
	fmt.Fprintf(&b, "case \"$OS_TYPE\" in\n")
	fmt.Fprintf(&b, "  linux)  OS=\"linux\" ;;\n")
	fmt.Fprintf(&b, "  darwin) OS=\"macos\" ;;\n")
	fmt.Fprintf(&b, "  *)\n")
	fmt.Fprintf(&b, "    echo \"Error: Unsupported operating system: $OS_TYPE\"\n")
	fmt.Fprintf(&b, "    exit 1\n")
	fmt.Fprintf(&b, "    ;;\n")
	fmt.Fprintf(&b, "esac\n\n")
	fmt.Fprintf(&b, "case \"$ARCH\" in\n")
	fmt.Fprintf(&b, "  x86_64|amd64) ARCH=\"amd64\" ;;\n")
	fmt.Fprintf(&b, "  aarch64|arm64) ARCH=\"arm64\" ;;\n")
	fmt.Fprintf(&b, "  *)\n")
	fmt.Fprintf(&b, "    echo \"Error: Unsupported architecture: $ARCH\"\n")
	fmt.Fprintf(&b, "    exit 1\n")
	fmt.Fprintf(&b, "    ;;\n")
	fmt.Fprintf(&b, "esac\n\n")
	fmt.Fprintf(&b, "echo \"Detected OS: $OS ($ARCH)\"\n\n")
	fmt.Fprintf(&b, "BINARY_NAME=\"ainms-agent\"\n")
	fmt.Fprintf(&b, "INSTALL_DIR=\"/usr/local/bin\"\n")
	fmt.Fprintf(&b, "DOWNLOAD_URL=\"${SERVER}/v1/agent/download?os=${OS}\u0026arch=${ARCH}\"\n\n")
	fmt.Fprintf(&b, "echo \"Downloading agent from ${DOWNLOAD_URL}...\"\n")
	fmt.Fprintf(&b, "if command -v curl \u0026\u003e/dev/null; then\n")
	fmt.Fprintf(&b, "  curl -fsSL -o \"${INSTALL_DIR}/${BINARY_NAME}\" \"${DOWNLOAD_URL}\" 2\u003e/dev/null || {\n")
	fmt.Fprintf(&b, "    echo \"Warning: Binary download not yet available. Skipping binary installation.\"\n")
	fmt.Fprintf(&b, "    echo \"The agent binary will need to be installed manually.\"\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "elif command -v wget \u0026\u003e/dev/null; then\n")
	fmt.Fprintf(&b, "  wget -q -O \"${INSTALL_DIR}/${BINARY_NAME}\" \"${DOWNLOAD_URL}\" 2\u003e/dev/null || {\n")
	fmt.Fprintf(&b, "    echo \"Warning: Binary download not yet available. Skipping binary installation.\"\n")
	fmt.Fprintf(&b, "    echo \"The agent binary will need to be installed manually.\"\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "fi\n\n")
	fmt.Fprintf(&b, "if [ -f \"${INSTALL_DIR}/${BINARY_NAME}\" ]; then\n")
	fmt.Fprintf(&b, "  chmod +x \"${INSTALL_DIR}/${BINARY_NAME}\"\n")
	fmt.Fprintf(&b, "fi\n\n")
	fmt.Fprintf(&b, "echo \"Enrolling device with install token...\"\n")
	fmt.Fprintf(&b, "ENROLLResp=$(${BINARY_NAME} --install-token \"$TOKEN\" --server \"$SERVER\" install 2\u003e/dev/null) || {\n")
	fmt.Fprintf(&b, "  echo \"Falling back to API enrollment...\"\n")
	fmt.Fprintf(&b, "  ENROLLResp=$(curl -fsSL -X POST \"${SERVER}/v1/enroll/token\" \\\n")
	fmt.Fprintf(&b, "    -H \"Content-Type: application/json\" \\\n")
	fmt.Fprintf(&b, "    -d \"{\\\"install_token\\\":\\\"$TOKEN\\\",\\\"os_type\\\":\\\"$OS\\\",\\\"hostname\\\":\\\"$(hostname 2\u003e/dev/null || echo unknown)\\\"}\" 2\u003e/dev/null) || {\n")
	fmt.Fprintf(&b, "    echo \"Error: Enrollment failed\"\n")
	fmt.Fprintf(&b, "    exit 1\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "  echo \"Device enrolled successfully via API\"\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "echo \"$ENROLLResp\"\n\n")
	fmt.Fprintf(&b, "echo \"Starting AINMS agent service...\"\n")
	fmt.Fprintf(&b, "if [ \"$OS\" = \"linux\" ]; then\n")
	fmt.Fprintf(&b, "  if command -v systemctl \u0026\u003e/dev/null; then\n")
	fmt.Fprintf(&b, "    cat \u003e /etc/systemd/system/ainms-agent.service \u003c\u003cEOF\n")
	fmt.Fprintf(&b, "[Unit]\n")
	fmt.Fprintf(&b, "Description=AINMS Agent\n")
	fmt.Fprintf(&b, "After=network.target\n\n")
	fmt.Fprintf(&b, "[Service]\n")
	fmt.Fprintf(&b, "Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=${INSTALL_DIR}/${BINARY_NAME} start\n")
	fmt.Fprintf(&b, "Restart=always\n")
	fmt.Fprintf(&b, "RestartSec=5\n\n")
	fmt.Fprintf(&b, "[Install]\n")
	fmt.Fprintf(&b, "WantedBy=multi-user.target\n")
	fmt.Fprintf(&b, "EOF\n")
	fmt.Fprintf(&b, "    systemctl daemon-reload\n")
	fmt.Fprintf(&b, "    systemctl enable ainms-agent\n")
	fmt.Fprintf(&b, "    systemctl start ainms-agent\n")
	fmt.Fprintf(&b, "    echo \"AINMS agent service started via systemd\"\n")
	fmt.Fprintf(&b, "  else\n")
	fmt.Fprintf(&b, "    nohup ${INSTALL_DIR}/${BINARY_NAME} start \u0026\u003e/var/log/ainms-agent.log \u0026\n")
	fmt.Fprintf(&b, "    echo \"AINMS agent started in background\"\n")
	fmt.Fprintf(&b, "  fi\n")
	fmt.Fprintf(&b, "elif [ \"$OS\" = \"macos\" ]; then\n")
	fmt.Fprintf(&b, "  if command -v launchctl \u0026\u003e/dev/null; then\n")
	fmt.Fprintf(&b, "    cat \u003e /Library/LaunchDaemons/com.ainms.agent.plist \u003c\u003cEOF\n")
	fmt.Fprintf(&b, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	fmt.Fprintf(&b, "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"\u003e\n")
	fmt.Fprintf(&b, "<plist version=\"1.0\"\u003e\n")
	fmt.Fprintf(&b, "<dict\u003e\n")
	fmt.Fprintf(&b, "  <key\u003eLabel\u003c/key\u003e\n")
	fmt.Fprintf(&b, "    <string\u003ecom.ainms.agent\u003c/string\u003e\n")
	fmt.Fprintf(&b, "  <key\u003eProgramArguments\u003c/key\u003e\n")
	fmt.Fprintf(&b, "  <array\u003e\n")
	fmt.Fprintf(&b, "    <string\u003e${INSTALL_DIR}/${BINARY_NAME}\u003c/string\u003e\n")
	fmt.Fprintf(&b, "    <string\u003estart\u003c/string\u003e\n")
	fmt.Fprintf(&b, "  </array\u003e\n")
	fmt.Fprintf(&b, "  <key\u003eRunAtLoad\u003c/key\u003e\n")
	fmt.Fprintf(&b, "  <true/\u003e\n")
	fmt.Fprintf(&b, "  <key\u003eKeepAlive\u003c/key\u003e\n")
	fmt.Fprintf(&b, "  <true/\u003e\n")
	fmt.Fprintf(&b, "</dict\u003e\n")
	fmt.Fprintf(&b, "</plist\u003e\n")
	fmt.Fprintf(&b, "EOF\n")
	fmt.Fprintf(&b, "    launchctl load /Library/LaunchDaemons/com.ainms.agent.plist\n")
	fmt.Fprintf(&b, "    echo \"AINMS agent service started via launchd\"\n")
	fmt.Fprintf(&b, "  else\n")
	fmt.Fprintf(&b, "    nohup ${INSTALL_DIR}/${BINARY_NAME} start \u0026\u003e/tmp/ainms-agent.log \u0026\n")
	fmt.Fprintf(&b, "    echo \"AINMS agent started in background\"\n")
	fmt.Fprintf(&b, "  fi\n")
	fmt.Fprintf(&b, "fi\n\n")
	fmt.Fprintf(&b, "echo \"=== Installation Complete ===\"\n")

	script := b.String()
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
		w.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(script))
	}
}
